# Extra env variables
# env = MY_GLOBAL_ENV,setting
env = XMODIFIERS,@im=fcitx
env = OMARCHY_SCREENSHOT_DIR, $HOME/Pictures/screenshots
env = LIBVA_DRIVER_NAME,iHD
env = VDPAU_DRIVER,va_gl
env = MESA_LOADER_DRIVER_OVERRIDE,zink  # Thử bỏ dòng này nếu game lỗi, nhưng zink giúp OpenGL chạy trên Vulkan khá tốt