# Extra autostart processes

# exec-once = uwsm-app -- my-service
exec-once = sleep 1 && hyprpm reload

# 1. Turn light ON immediately at startup
exec-once = /home/hittake/.config/hypr/scripts/kb-light.sh on

# 2. Handle Idle (Turn OFF after 10s, ON when you return)
exec-once = swayidle -w timeout 10 '/home/hittake/.config/hypr/scripts/kb-light.sh off' resume '/home/YOUR_USERNAME/.config/hypr/scripts/kb-light.sh on'