general {
    lock_cmd = omarchy-lock-screen                         # lock screen and 1password
    before_sleep_cmd = loginctl lock-session               # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on             # to avoid having to press a key twice to turn on the display.
    inhibit_sleep = 3     # wait until screen is locked
    ignore_dbus_inhibit = false 
}


listener {
    timeout = 1200                    
    on-timeout = loginctl lock-session # lock screen when timeout has passed
}

listener {
    timeout = 1100                                            # 5.5min
    on-timeout = hyprctl dispatch dpms off                   # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on && brightnessctl -r # screen on when activity is detected
}
listener {
    timeout = 10                                # 10 seconds
    on-timeout = brightnessctl -d platform::kbd_backlight set 0
    on-resume = brightnessctl -d platform::kbd_backlight set 100%
}
